[package]
name = "gibberish-runtime"
version = "0.1.0"
edition = "2024"
license = "MIT"                                                             # or whatever you actually use
repository = "https://github.com/mnbjhu/gibberish/crates/gibberish_runtime"
readme = "README.md"

[dependencies]
gibberish-core = { path = "../gibberish_core/" }
